
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env  # optional; if you have DB URL, CORS origins, etc.
    restart: unless-stopped
    container_name: arrivals-backend
    # WebSocket-capable worker on 8081
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 2 --timeout 90 -b 0.0.0.0:8081 app:app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Podgorica
      - MAIL_DEBUG=0
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://arrivals:supersecretchangeit@db:5432/arrivals}
      - UPLOAD_DIR=/app/uploads
      - API_KEY=devkey123
      - ALLOWED_ORIGINS=http://localhost:5173
      - LOG_HTTP=1
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:16-alpine
    container_name: arrivals-postgres
    environment:
      POSTGRES_DB: arrivals
      POSTGRES_USER: arrivals
      POSTGRES_PASSWORD: supersecretchangeit
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arrivals -d arrivals"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes: {}
