
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env  # optional; if you have DB URL, CORS origins, etc.
    restart: unless-stopped
    container_name: arrivals-backend
    # WebSocket-capable worker on 8081
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 2 --timeout 90 -b 0.0.0.0:8081 app:app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - TZ=Europe/Podgorica
      - MAIL_DEBUG=0
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://arrivals:supersecretchangeit@db:5432/arrivals}
      - UPLOAD_DIR=/app/uploads
      - AUTO_CREATE_TABLES=0
      - API_KEY=devkey123
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - LOG_HTTP=1
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      - CACHE_REDIS_URL=${CACHE_REDIS_URL:-redis://redis:6379/0}
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

  db:
    image: postgres:16-alpine
    container_name: arrivals-postgres
    environment:
      POSTGRES_DB: arrivals
      POSTGRES_USER: arrivals
      POSTGRES_PASSWORD: supersecretchangeit
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arrivals -d arrivals"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: arrivals-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://arrivals:supersecretchangeit@db:5432/arrivals}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      - CACHE_REDIS_URL=${CACHE_REDIS_URL:-redis://redis:6379/0}
    command: celery -A celery_app.celery_app worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes: {}
