[tool.black]
line-length = 100
target-version = ["py311"]
exclude = [
  "migrations",
  "data",
  "uploads",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["migrations", "data", "uploads"]

